globalThis.siteConfig = {
	bottomLinks: ``,
	title: ``,
	server_url: ``,
	about_us: ``,
	donate: ``,
	cardPush: ``,
	offlineToUse: ``,
	sourceStoreFrom: ``,
	homePageLimit: ``,
	userRegister: ``,
	loginBackground: ``,
	loginBackgroundBlur: ``,
	loginBackgroundBrightness: ``,
	uploadWallpaper: ``,
	uploadWallpaperMaxSize: ``,
};
