export const SITE_CONFIG = {
  bottomLinks: '[{"label":"DTab · 本地数据保存在当前浏览器","link":"/"}]',
  title: 'DTab · 本地版',
  server_url: '',
  about_us: 'DTab：界面与数据结构沿用原版；账号与云端同步在侧边栏「迁移备份」中配置。',
  donate: '',
  cardPush: 'close',
  offlineToUse: 'open',
  sourceStoreFrom: 'self',
  homePageLimit: 'close',
  userRegister: 'close',
  loginBackground: '',
  loginBackgroundBlur: '',
  loginBackgroundBrightness: '',
  uploadWallpaper: 'close',
  uploadWallpaperMaxSize: '0',
};
